name: Validation
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 2

      - name: setup python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install -q --upgrade pip
          python -m pip install -q -r requirements.txt
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          enviroment-file: environment.yml
          python-version: 3.9
          miniforge-version: latest

      - name: Valudate code 
        shell: bash -l {0}
        run: |
          python3 testing_dns.py 
     #     pytest
