name: jupyter-actions
channels:
    - conda-forge
dependencies:
    - nbformat
    - nbconvert
    - requests=2.24.0
    - pytest
    - ipykernel=5.3.4
    - ipython=7.22.0
    - ipython_genutils=0.2.0
    - jupyter=1.0.0
    - jupyter-packaging=0.7.12
    - jupyter_client=6.1.12
    - jupyter_console=6.4.0
    - jupyter_core=4.7.1
    - jupyter_server=1.4.1
    - jupyterlab=3.0.14
    - jupyterlab_pygments=0.1.2
    - jupyterlab_server=2.4.0
    - jupyterlab_widgets=1.0.0
    - jupyter_contrib_nbextensions=0.5.1
    - matplotlib
    - matplotlib-base
    - nose=1.3.7
    - numpy=1.20.1
    - numpy-base=1.20.1
    - numpydoc=1.1.0
    - pandas=1.2.4
    - sympy=1.8
